Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
"GET / HTTP/1.1" 200 274
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /about HTTP/1.1" 200 368
"GET / HTTP/1.1" 200 274
"GET /my_games/coin HTTP/1.1" 200 118
"GET /my_games/ HTTP/1.1" 200 107
"GET /my_games/coin HTTP/1.1" 200 118
"GET /my_games/ HTTP/1.1" 200 107
"GET /my_games/dice HTTP/1.1" 200 155
"GET /my_games/dice HTTP/1.1" 200 155
"GET /my_games/ HTTP/1.1" 200 107
"GET /my_games/random HTTP/1.1" 200 126
"GET /my_games/random HTTP/1.1" 200 126
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
Not Found: /hw3/products/3
"GET /hw3/products/3 HTTP/1.1" 404 3188
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hw3/products/3
"GET /hw3/products/3 HTTP/1.1" 404 3188
Not Found: /hw3/products/3
"GET /hw3/products/3 HTTP/1.1" 404 3188
Not Found: /hw3/products
"GET /hw3/products HTTP/1.1" 404 3182
Not Found: /hw3/products/1
"GET /hw3/products/1 HTTP/1.1" 404 3188
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/products/1 HTTP/1.1" 301 0
"GET /hw3/products/1/ HTTP/1.1" 200 1609
Not Found: /products/
"GET /products/ HTTP/1.1" 404 3067
Not Found: /products/3
"GET /products/3 HTTP/1.1" 404 3070
"GET /hw3/products/3 HTTP/1.1" 301 0
"GET /hw3/products/3/ HTTP/1.1" 200 1609
"GET /hw3/products/1/ HTTP/1.1" 200 1609
"GET /hw3/products/1/ HTTP/1.1" 200 1609
"GET /hw3/products/1/ HTTP/1.1" 200 1609
"GET /hw3/products/1/ HTTP/1.1" 200 1609
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /hw3/products/1/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 34, in unique_products_ordered
    return render(request, 'client_products.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_products.html
"GET /hw3/products/1/ HTTP/1.1" 500 78820
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hw3//1/
"GET /hw3//1/ HTTP/1.1" 404 3175
Internal Server Error: /hw3/client/2/orders
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 34, in unique_products_ordered
    return render(request, 'client_products.html', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: client_products.html
"GET /hw3/client/2/orders HTTP/1.1" 500 78203
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/client/2/orders HTTP/1.1" 200 1103
"GET /hw3/client/1/orders HTTP/1.1" 200 1103
"GET /hw3/client/3/orders HTTP/1.1" 200 1103
"GET /hw3/client/4/orders HTTP/1.1" 200 1103
"GET /hw3/client/7/orders HTTP/1.1" 200 1103
"GET /hw3/client/10/orders HTTP/1.1" 200 1106
Watching for file changes with StatReloader
"GET /hw3/client/10/orders HTTP/1.1" 200 1106
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 13, in client_ordered_products
    orders = Order.objects.filter(client_id=client_id, date_ordered__range=(start_date, end_date))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1476, in filter
    return self._filter_or_exclude(False, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1494, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/query.py", line 1501, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1613, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1645, in _add_q
    child_clause, needed_inner = self.build_filter(
                                 ^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1495, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg, summarize)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1307, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/db/models/sql/query.py", line 1772, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'client_id' into field. Choices are: customer, customer_id, date_ordered, id, products, total_price
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 115745
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: client_ordered_products() got an unexpected keyword argument 'client_id'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 56218
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: client_ordered_products() got an unexpected keyword argument 'client_id'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 56218
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.order_date, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.order_date, reverse=True)
                                                                            ^^^^^^^
AttributeError: 'Product' object has no attribute 'order'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 66961
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.date_ordered, reverse=True)
                                                                            ^^^^^^^
AttributeError: 'Product' object has no attribute 'order'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 66973
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.date_ordered, reverse=True)
                                                                            ^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'date_ordered'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 66979
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order_id.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order_id.date_ordered, reverse=True)
                                                                            ^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'order_id'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 67009
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order_id.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order_id.date_ordered, reverse=True)
                                                                            ^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'order_id'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 67009
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/7/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.name.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.name.date_ordered, reverse=True)
                                                                            ^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'date_ordered'
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 500 67003
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/clients/1/ordered_products/7/ HTTP/1.1" 200 1365
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 200 1367
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 200 773
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 200 773
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/1/ordered_products/365/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.date_ordered, reverse=True)
                                                                            ^^^^^^^^^^^^^^
AttributeError: 'Product' object has no attribute 'date_ordered'
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 500 67320
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 200 1367
"GET /hw3/clients/1/ordered_products/365/ HTTP/1.1" 200 1367
"GET /hw3/clients/2/ordered_products/365/ HTTP/1.1" 200 1237
"GET /hw3/clients/3/ordered_products/365/ HTTP/1.1" 200 1103
"GET /hw3/clients/4/ordered_products/365/ HTTP/1.1" 200 1237
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /hw3/clients/4/ordered_products/365/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in client_ordered_products
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.date_ordered, reverse=True)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 24, in <lambda>
    sorted_ordered_products = sorted(unique_ordered_products, key=lambda x: x.order.date_ordered, reverse=True)
                                                                            ^^^^^^^
AttributeError: 'Product' object has no attribute 'order'
"GET /hw3/clients/4/ordered_products/365/ HTTP/1.1" 500 66681
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/clients/4/ordered_products/365/ HTTP/1.1" 200 1237
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/client/4/products/ HTTP/1.1" 200 2745
"GET /hw3/client/1/products/ HTTP/1.1" 200 3258
"GET /hw3/client/2/products/ HTTP/1.1" 200 2745
"GET /hw3/client/3/products/ HTTP/1.1" 200 2226
"GET /hw3/client/4/products/ HTTP/1.1" 200 2745
Watching for file changes with StatReloader
"GET /hw3/client/4/products/ HTTP/1.1" 200 2745
"GET /hw3/client/1/products/ HTTP/1.1" 200 2226
"GET /hw3/client/1/products/ HTTP/1.1" 200 2343
"GET /hw3/client/1/products/ HTTP/1.1" 200 2346
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /hw3/client/1/products/ HTTP/1.1" 200 5052
"GET /hw3/client/1/products/ HTTP/1.1" 200 5052
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
"GET /hw3/client/3/products/ HTTP/1.1" 200 4977
"GET /hw3/client/3/products/ HTTP/1.1" 200 4989
"GET /hw3/client/3/products/ HTTP/1.1" 200 5139
"GET /hw3/client/3/products/ HTTP/1.1" 200 3294
Internal Server Error: /hw3/client/3/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 35, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 230, in render
    raise ValueError(
ValueError: Need 2 values to unpack in for loop; got 1. 
"GET /hw3/client/3/products/ HTTP/1.1" 500 224953
"GET /hw3/client/3/products/ HTTP/1.1" 200 5139
"GET /hw3/client/3/products/ HTTP/1.1" 200 5223
"GET /hw3/client/3/products/ HTTP/1.1" 200 5139
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 274
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2272
Not Found: /
"GET / HTTP/1.1" 404 2272
"GET /client/3/products HTTP/1.1" 301 0
"GET /client/3/products/ HTTP/1.1" 200 2673
"GET /client/6/products/ HTTP/1.1" 200 6292
Not Found: /products/
"GET /products/ HTTP/1.1" 404 2317
Not Found: /media/product_images/5J1F5ULz8E3td9U37o4DDRE_9O24wocOBkhc7yj9ke8.jpeg
Not Found: /media/product_images/myachik-antistress-malevich-oranzhevyy-263825-foto-0.jpg
"GET /media/product_images/5J1F5ULz8E3td9U37o4DDRE_9O24wocOBkhc7yj9ke8.jpeg HTTP/1.1" 404 2497
Not Found: /media/product_images/74903760299.jpg
"GET /media/product_images/myachik-antistress-malevich-oranzhevyy-263825-foto-0.jpg HTTP/1.1" 404 2521
"GET /media/product_images/74903760299.jpg HTTP/1.1" 404 2398
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/6/products/ HTTP/1.1" 200 6292
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'list_clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: list_clients.html
"GET / HTTP/1.1" 500 77076
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET / HTTP/1.1" 500 76827
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET / HTTP/1.1" 500 76827
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET / HTTP/1.1" 500 76768
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET / HTTP/1.1" 500 76768
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2448
"GET /client/6/products/ HTTP/1.1" 200 6292
"GET /clients HTTP/1.1" 301 0
Internal Server Error: /clients/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET /clients/ HTTP/1.1" 500 76864
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/3/products
"GET /clients/3/products HTTP/1.1" 404 2512
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/3/products
"GET /clients/3/products HTTP/1.1" 404 2239
Not Found: /clients/3/products
"GET /clients/3/products HTTP/1.1" 404 2239
Not Found: /hw3/clients/3/products
"GET /hw3/clients/3/products HTTP/1.1" 404 2532
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hw3/clients/3/products
"GET /hw3/clients/3/products HTTP/1.1" 404 2859
/Users/mac/Desktop/Django/my_project/my_project/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/3/products/ HTTP/1.1" 200 2673
"GET /client/3/products/ HTTP/1.1" 200 2673
"GET /client/3/products/ HTTP/1.1" 200 2673
"GET /client/3/products/ HTTP/1.1" 200 2673
Internal Server Error: /
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 9, in list_clients
    return render(request, 'clients.html', {'clients': clients})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: clients.html
"GET / HTTP/1.1" 500 76768
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1284
"GET /client/2/products/ HTTP/1.1" 200 4587
"GET / HTTP/1.1" 200 1644
"GET /client/1/products/ HTTP/1.1" 200 4033
"GET / HTTP/1.1" 200 1684
"GET / HTTP/1.1" 200 1734
"GET / HTTP/1.1" 200 1634
"GET / HTTP/1.1" 200 1634
"GET / HTTP/1.1" 200 1674
"GET / HTTP/1.1" 200 1674
"GET / HTTP/1.1" 200 1644
Not Found: /contact/
"GET /contact/ HTTP/1.1" 404 2482
"GET /client/5/products/ HTTP/1.1" 200 9162
"GET / HTTP/1.1" 200 1644
"GET / HTTP/1.1" 200 1684
"GET / HTTP/1.1" 200 1724
"GET /client/4/products/ HTTP/1.1" 200 5962
"GET /client/7/products/ HTTP/1.1" 200 9762
"GET /client/10/products/ HTTP/1.1" 200 7720
"GET /client/8/products/ HTTP/1.1" 200 9219
"GET /client/2/products/ HTTP/1.1" 200 4587
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 1724
"GET /client/1/products/ HTTP/1.1" 200 4033
"GET /client/4/products/ HTTP/1.1" 200 5462
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'clients.html' not found. 'clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 176987
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'clients.html' not found. 'clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 176987
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hwapp3/clients.html' not found. 'hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177162
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hwapp3/clients.html' not found. 'hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177162
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/templates/hwapp3/clients.html' not found. '/templates/hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177451
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/templates/hwapp3/clients.html' not found. '/templates/hwapp3/clients.html' is not a valid view function or pattern name.
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/templates/hwapp3/clients.html' not found. '/templates/hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177451
- Broken pipe from ('127.0.0.1', 59020)
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hwapp3/templates/hwapp3/clients.html' not found. 'hwapp3/templates/hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177596
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'hwapp3/templates/hwapp3/clients.html' not found. 'hwapp3/templates/hwapp3/clients.html' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 177596
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'clients' not found. 'clients' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 176857
Internal Server Error: /client/4/products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 37, in client_products
    return render(request, 'hwapp3/client_products.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 479, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/urls/resolvers.py", line 851, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'clients' not found. 'clients' is not a valid view function or pattern name.
"GET /client/4/products/ HTTP/1.1" 500 176862
"GET /client/4/products/ HTTP/1.1" 200 5397
"GET / HTTP/1.1" 200 1659
"GET / HTTP/1.1" 200 1680
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 777
"GET / HTTP/1.1" 200 762
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
"GET / HTTP/1.1" 200 762
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2651
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2651
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2652
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 762
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
Not Found: /clients/clients
"GET /clients/clients HTTP/1.1" 404 2671
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2650
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
/Users/mac/Desktop/Django/my_project/my_project/settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2651
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
Not Found: /clients/
"GET /clients/ HTTP/1.1" 404 2482
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 1683
"GET / HTTP/1.1" 200 763
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/1/products/ HTTP/1.1" 200 3992
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/10/products/ HTTP/1.1" 200 5779
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/8/products/ HTTP/1.1" 200 5135
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/9/products/ HTTP/1.1" 200 5099
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/3/products/ HTTP/1.1" 200 2632
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/2/products/ HTTP/1.1" 200 4546
"GET / HTTP/1.1" 200 763
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/4/products/ HTTP/1.1" 200 5421
"GET / HTTP/1.1" 200 763
"GET /clients/ HTTP/1.1" 200 1683
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /client/1/products/
"GET /client/1/products/ HTTP/1.1" 404 2665
/Users/mac/Desktop/Django/my_project/hwapp3/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clients/ HTTP/1.1" 200 1683
"GET /client/1/products/ HTTP/1.1" 200 3992
/Users/mac/Desktop/Django/my_project/hwapp3/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /client/1/products/ HTTP/1.1" 200 4059
Internal Server Error: /products/
Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 502, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/my_project/hwapp3/views.py", line 46, in all_products
    return render(request, 'hwapp3/products.html', {'products': products})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 295, in do_extends
    nodelist = parser.parse()
               ^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/loader_tags.py", line 234, in do_block
    nodelist = parser.parse(("endblock",))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 504, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/Users/mac/Desktop/Django/venv/lib/python3.11/site-packages/django/template/base.py", line 555, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 13: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
"GET /products/ HTTP/1.1" 500 170815
"GET /products/ HTTP/1.1" 200 1356
"GET /products/ HTTP/1.1" 200 1356
"GET /products/ HTTP/1.1" 200 1366
"GET /clients/ HTTP/1.1" 200 1750
"GET /products/ HTTP/1.1" 200 1366
"GET /clients/ HTTP/1.1" 200 1750
"GET / HTTP/1.1" 200 830
"GET /clients/ HTTP/1.1" 200 1750
"GET /products/ HTTP/1.1" 200 1366
"GET /clients/ HTTP/1.1" 200 1750
"GET /client/1/products/ HTTP/1.1" 200 4059
